In [2]:
import numpy as np

# ----------------------------
# Step 1: Define "embeddings"
# ----------------------------
# 3 tokens, embedding dimension = 4
X = np.array([
    [1.0, 0.0, 1.0, 0.0],  # token 1 (e.g., "He")
    [0.0, 1.0, 0.0, 1.0],  # token 2 (e.g., "ate")
    [1.0, 1.0, 0.0, 0.0]   # token 3 (e.g., "apple")
])

# ----------------------------
# Step 2: Define projection matrices
# ----------------------------
np.random.seed(42)

W_Q = np.random.rand(4, 4)
W_K = np.random.rand(4, 4)
W_V = np.random.rand(4, 4)

# ----------------------------
# Step 3: Compute Q, K, V
# ----------------------------
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

print("Q:\n", Q)
print("\nK:\n", K)
print("\nV:\n", V)

# ----------------------------
# Step 4: Compute attention scores
# ----------------------------
scores = Q @ K.T #Transpose K to get dot product between Q and K (all keys (all tokens in the sequence))

# Scale 
d_k = K.shape[1]
scores = scores / np.sqrt(d_k)

print("\nAttention Scores:\n", scores)

# ----------------------------
# Step 5: Softmax
# ----------------------------
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

weights = softmax(scores)

print("\nAttention Weights:\n", weights)

# ----------------------------
# Step 6: Compute output
# ----------------------------
# weighted sum of V using attention weights
output = weights @ V

print("\nFinal Output (Contextualized Representations):\n", output)

Q:
 [[0.97565513 1.65878688 0.75257844 1.56856834]
 [0.98846128 0.36833363 0.23990858 1.04958066]
 [0.53055876 1.10670883 0.79007755 1.46483463]]

K:
 [[0.76031223 1.30993239 0.6316188  0.80546358]
 [1.20426746 0.18594427 0.8996895  0.53688597]
 [0.91609514 0.66425029 0.72408967 0.65759098]]

V:
 [[0.18708983 1.44406245 1.00002055 1.71771775]
 [0.56339375 0.7601944  0.9959441  0.96022051]
 [0.36966536 1.04655765 1.64986506 1.24854984]]

Attention Scores:
 [[2.32673428 1.50131045 1.78602663]
 [1.11548056 1.01910482 1.0070502 ]
 [1.76600142 1.17099723 1.3782615 ]]

Attention Weights:
 [[0.49495509 0.21681473 0.28823018]
 [0.35645997 0.3237094  0.31983063]
 [0.44840052 0.24731991 0.30427957]]

Final Output (Contextualized Representations):
 [[0.32130184 1.1812169  1.18644152 1.41825284]
 [0.36729619 1.09555372 1.20654115 1.32245451]
 [0.33571128 1.15397568 1.19674678 1.38761539]]
